import streamlit as st

st.title('Data Analysis with SQL')

st.divider()

st.subheader('Practising your SQL skills by analyzing data')

st.write('###')

st.write('All SQL Tutorials in this portal were created using Microsoft SQL Server.')

st.write('###')

col1, col2, col3 = st.columns([2, 5, 2])

col2.image('images\SQL-data-reports.png', caption='Generated by Microsoft Copilot', width=300)
